#!/usr/bin/env python2
#

import subprocess
import argparse
import sys

# patchwork related libs
from mbox import Mbox
#from tests import Tests

def get_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--test-file', type=str, dest='test_file',
                        help="File containing the a test case to execute")
    parser.add_argument('--test-directory', type=str, dest='test_dir',
                        help="Directory containing the test cases to execute")
    parser.add_argument('--pw-url', type=str, dest='pw_url',
                        default='https://patchwork.freedesktop.org',
                        help="Patchwork web instance")
    parser.add_argument('--workspace-directory', type=str, dest='workspace_dir',
                        default='/tmp/testpatch',
                        help="The workspace directory")
    parser.add_argument('--pw-project', type=str, dest='pw_project',
                        default='beignet', help="Patchwork project")
    parser.add_argument('--series', dest='series',
                        help='Specify the series number. If present, the "--since" argument is ignored')
    parser.add_argument('--since', dest='since', default='last',
                        help='Specify the range of series to tests')

    return parser

def main(args):
    mbox = Mbox(args.workspace_dir,
                args.pw_project,
                args.since,
                args.series)

    mbox.download()
    mbox.clone_repo()
    mbox.patch()

    return 0

if __name__ == '__main__':
    ret = main(get_parser().parse_args())
    sys.exit(ret)
